### PR TITLE
fix: make highlights youtube video iframe responsive

### LINKED ISSUE #21: MTA Hack 2019 highlights video is stretched
The MTA Hack 2019 highlights video is stretched. CSS needs fixing.
[Video link](https://mtahack.com/#highlights)
Screen Shot 2021-03-01 at 12 16 36

### PR DESCRIPTION
**Pull request by talkor**
resolves #21

### CODE REVIEW

**Review by nadavsu — APPROVED** [review]

**Comment by nadavsu** [comment]
Thanks!

**Comment by nadavsu** [comment]
Also, I want to make sure that I understood what you did there. 
You created a new section for the iframe, with 16:9 aspect ratio, and then 'filled' it with the iframe itself. Is that right?

**Comment by talkor** [comment]
That's right, this is actually a hack: https://www.w3schools.com/howto/howto_css_responsive_iframes.asp

**Comment by nadavsu** [comment]
Nice. Good to know.

**Pull request merged**
